#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'
shopt -s nullglob nocaseglob

# modern bash version check
! [ "${BASH_VERSINFO:-0}" -ge 4 ] && echo "This script requires bash v4 or later" && exit 1

# path to self and parent dir
SCRIPT=$(realpath $0)
SCRIPTPATH=$(dirname $SCRIPT)

# check that target directory is provided and exists
if [ $# -ne 1 ]; then
  echo "Usage: $0 <target_dir>"
  exit 1
fi

TARGET_DIR=$1

if [ ! -d $TARGET_DIR ]; then
  echo "Target directory does not exist: $TARGET_DIR"
  exit 1
fi

# Delete matching files
echo "Deleting evining files in $TARGET_DIR"
find "$TARGET_DIR" -name "240*-2[0-4]*" -type f -delete

echo "Deleting morning files in $TARGET_DIR"
find "$TARGET_DIR" -name "240*-0[0-6]*" -type f -delete

exit 0